name: safereport_mobo
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  image_picker: ^1.0.4
  flutter_sound: ^9.2.13
  permission_handler: ^12.0.1
  path_provider: ^2.1.1
  video_compress: ^3.1.2
  connectivity_plus: ^7.0.0
  fl_chart: ^1.1.1
  pdf: ^3.10.4
  printing: ^5.11.0
  share_plus: ^12.0.1
  cross_file: ^0.3.4
  url_launcher: ^6.3.0
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  http: ^1.2.0
  dio: ^5.4.0
  provider: ^6.1.1
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  google_maps_flutter: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/images/

